variable "region" {}
variable "availability_zone1" {}
variable "availability_zone2" {}
variable "vpc_id" {}
variable "vpc_cidr" {}
variable "public_subnet1_id" {}
variable "private_subnet1_id" {}
variable "public_subnet2_id" {}
variable "private_subnet2_id" {}
variable "instance_type" {}
variable "cidr_for_access" {}
variable "keypair" {}
variable "encrypt_volumes" {}
variable "fortios_version" {}
variable "fgt_bgp_asn" {}
variable "license_type" {}
variable "fgt1_byol_license" {}
variable "fgt2_byol_license" {}
variable "fgt1_fortiflex_token" {}
variable "fgt2_fortiflex_token" {}
variable "tgw_connect_cidr" {}
variable "tgw_bgp_asn" {}
variable "tgw_connect_attachment_id" {}
variable "tgw_connect_peer1_inside_cidr" {}
variable "tgw_connect_peer2_inside_cidr" {}
variable "tag_name_prefix" {}